[project]
name = "exammagicutilities"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "dotenv>=0.9.9",
    "flask>=3.1.2",
    "gradio>=6.0.1",
    "openai>=2.8.1",
    "pdf2image>=1.17.0",
    "requests>=2.32.5",
]
